#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinApp.BD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD1")]
	public partial class ProyectoDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertBodegas(Bodegas instance);
    partial void UpdateBodegas(Bodegas instance);
    partial void DeleteBodegas(Bodegas instance);
    partial void InsertCapillas(Capillas instance);
    partial void UpdateCapillas(Capillas instance);
    partial void DeleteCapillas(Capillas instance);
    partial void InsertEdificioTB(EdificioTB instance);
    partial void UpdateEdificioTB(EdificioTB instance);
    partial void DeleteEdificioTB(EdificioTB instance);
    partial void InsertEnseres(Enseres instance);
    partial void UpdateEnseres(Enseres instance);
    partial void DeleteEnseres(Enseres instance);
    partial void InsertEspacioTB(EspacioTB instance);
    partial void UpdateEspacioTB(EspacioTB instance);
    partial void DeleteEspacioTB(EspacioTB instance);
    partial void InsertInsidencias(Insidencias instance);
    partial void UpdateInsidencias(Insidencias instance);
    partial void DeleteInsidencias(Insidencias instance);
    partial void InsertParqueos(Parqueos instance);
    partial void UpdateParqueos(Parqueos instance);
    partial void DeleteParqueos(Parqueos instance);
    partial void InsertRoles(Roles instance);
    partial void UpdateRoles(Roles instance);
    partial void DeleteRoles(Roles instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertTBusers(TBusers instance);
    partial void UpdateTBusers(TBusers instance);
    partial void DeleteTBusers(TBusers instance);
    #endregion
		
		public ProyectoDataClassesDataContext() : 
				base(global::WinApp.Properties.Settings.Default.BD1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bodegas> Bodegas
		{
			get
			{
				return this.GetTable<Bodegas>();
			}
		}
		
		public System.Data.Linq.Table<Capillas> Capillas
		{
			get
			{
				return this.GetTable<Capillas>();
			}
		}
		
		public System.Data.Linq.Table<EdificioTB> EdificioTB
		{
			get
			{
				return this.GetTable<EdificioTB>();
			}
		}
		
		public System.Data.Linq.Table<Enseres> Enseres
		{
			get
			{
				return this.GetTable<Enseres>();
			}
		}
		
		public System.Data.Linq.Table<EspacioTB> EspacioTB
		{
			get
			{
				return this.GetTable<EspacioTB>();
			}
		}
		
		public System.Data.Linq.Table<Insidencias> Insidencias
		{
			get
			{
				return this.GetTable<Insidencias>();
			}
		}
		
		public System.Data.Linq.Table<Parqueos> Parqueos
		{
			get
			{
				return this.GetTable<Parqueos>();
			}
		}
		
		public System.Data.Linq.Table<Roles> Roles
		{
			get
			{
				return this.GetTable<Roles>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<TBusers> TBusers
		{
			get
			{
				return this.GetTable<TBusers>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Actualizar_Enser")]
		public int Actualizar_Enser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Marca", DbType="NVarChar(15)")] string marca, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="NVarChar(10)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEstado", DbType="Int")] System.Nullable<int> dEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Espacio", DbType="NVarChar(10)")] string espacio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, marca, tipo, dEstado, espacio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Actualizar_espacio")]
		public int Actualizar_espacio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="Char(15)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Capacidad", DbType="Int")] System.Nullable<int> capacidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dimenciones", DbType="VarChar(10)")] string dimenciones, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edicifio", DbType="NVarChar(10)")] string edicifio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tipo, capacidad, dimenciones, estado, edicifio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Eliminar_Enser")]
		public int Eliminar_Enser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEstado", DbType="Int")] System.Nullable<int> dEstado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, dEstado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Eliminar_espacio")]
		public int Eliminar_espacio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insertar_Enser")]
		public int Insertar_Enser([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Marca", DbType="NVarChar(15)")] string marca, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="NVarChar(10)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Espacio", DbType="NVarChar(10)")] string espacio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, marca, tipo, espacio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insertar_Espacio")]
		public int Insertar_Espacio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo", DbType="Char(15)")] string tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Capacidad", DbType="Int")] System.Nullable<int> capacidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dimenciones", DbType="VarChar(10)")] string dimenciones, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edicifio", DbType="NVarChar(10)")] string edicifio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tipo, capacidad, dimenciones, estado, edicifio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarEdificios")]
		public ISingleResult<ListarEdificiosResult> ListarEdificios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarEdificiosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarEnseres")]
		public ISingleResult<ListarEnseresResult> ListarEnseres()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarEnseresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarEspacios")]
		public ISingleResult<ListarEspaciosResult> ListarEspacios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarEspaciosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Eliminar_User")]
		public int Eliminar_User([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Actualizar_User")]
		public int Actualizar_User([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(25)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dire", DbType="NVarChar(50)")] string dire, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tele", DbType="Int")] System.Nullable<int> tele, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edificio", DbType="NVarChar(10)")] string edificio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rol", DbType="Int")] System.Nullable<int> rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, user, pass, dire, tele, email, estado, edificio, rol);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Actualizar_Rol")]
		public int Actualizar_Rol([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="Char(15)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="Text")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Int")] System.Nullable<int> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Salario", DbType="Money")] System.Nullable<decimal> salario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, descripcion, estado, salario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Eliminar_Rol")]
		public int Eliminar_Rol([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="Int")] System.Nullable<int> estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insertar_Rol")]
		public int Insertar_Rol([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="Char(15)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="Text")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Salario", DbType="Money")] System.Nullable<decimal> salario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nombre, descripcion, salario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarUser")]
		public ISingleResult<ListarUserResult> ListarUser()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insertar_User")]
		public int Insertar_User([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(25)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Dire", DbType="NVarChar(50)")] string dire, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tele", DbType="Int")] System.Nullable<int> tele, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Edificio", DbType="NVarChar(10)")] string edificio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rol", DbType="Int")] System.Nullable<int> rol)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, user, pass, dire, tele, email, estado, edificio, rol);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bodegas")]
	public partial class Bodegas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Bodega;
		
		private string _Dimenciones;
		
		private string _Descripcion;
		
		private int _Estado;
		
		private string _ID_Edificio;
		
		private EntityRef<EdificioTB> _EdificioTB;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BodegaChanging(string value);
    partial void OnID_BodegaChanged();
    partial void OnDimencionesChanging(string value);
    partial void OnDimencionesChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnID_EdificioChanging(string value);
    partial void OnID_EdificioChanged();
    #endregion
		
		public Bodegas()
		{
			this._EdificioTB = default(EntityRef<EdificioTB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Bodega", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Bodega
		{
			get
			{
				return this._ID_Bodega;
			}
			set
			{
				if ((this._ID_Bodega != value))
				{
					this.OnID_BodegaChanging(value);
					this.SendPropertyChanging();
					this._ID_Bodega = value;
					this.SendPropertyChanged("ID_Bodega");
					this.OnID_BodegaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dimenciones", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Dimenciones
		{
			get
			{
				return this._Dimenciones;
			}
			set
			{
				if ((this._Dimenciones != value))
				{
					this.OnDimencionesChanging(value);
					this.SendPropertyChanging();
					this._Dimenciones = value;
					this.SendPropertyChanged("Dimenciones");
					this.OnDimencionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10)")]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					if (this._EdificioTB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EdificioChanging(value);
					this.SendPropertyChanging();
					this._ID_Edificio = value;
					this.SendPropertyChanged("ID_Edificio");
					this.OnID_EdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_Bodegas", Storage="_EdificioTB", ThisKey="ID_Edificio", OtherKey="ID_Edificio", IsForeignKey=true)]
		public EdificioTB EdificioTB
		{
			get
			{
				return this._EdificioTB.Entity;
			}
			set
			{
				EdificioTB previousValue = this._EdificioTB.Entity;
				if (((previousValue != value) 
							|| (this._EdificioTB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EdificioTB.Entity = null;
						previousValue.Bodegas.Remove(this);
					}
					this._EdificioTB.Entity = value;
					if ((value != null))
					{
						value.Bodegas.Add(this);
						this._ID_Edificio = value.ID_Edificio;
					}
					else
					{
						this._ID_Edificio = default(string);
					}
					this.SendPropertyChanged("EdificioTB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Capillas")]
	public partial class Capillas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Capilla;
		
		private int _Cap_Personas;
		
		private string _Dimenciones;
		
		private int _Estado;
		
		private string _ID_Edificio;
		
		private EntityRef<EdificioTB> _EdificioTB;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CapillaChanging(string value);
    partial void OnID_CapillaChanged();
    partial void OnCap_PersonasChanging(int value);
    partial void OnCap_PersonasChanged();
    partial void OnDimencionesChanging(string value);
    partial void OnDimencionesChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnID_EdificioChanging(string value);
    partial void OnID_EdificioChanged();
    #endregion
		
		public Capillas()
		{
			this._EdificioTB = default(EntityRef<EdificioTB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Capilla", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Capilla
		{
			get
			{
				return this._ID_Capilla;
			}
			set
			{
				if ((this._ID_Capilla != value))
				{
					this.OnID_CapillaChanging(value);
					this.SendPropertyChanging();
					this._ID_Capilla = value;
					this.SendPropertyChanged("ID_Capilla");
					this.OnID_CapillaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap_Personas", DbType="Int NOT NULL")]
		public int Cap_Personas
		{
			get
			{
				return this._Cap_Personas;
			}
			set
			{
				if ((this._Cap_Personas != value))
				{
					this.OnCap_PersonasChanging(value);
					this.SendPropertyChanging();
					this._Cap_Personas = value;
					this.SendPropertyChanged("Cap_Personas");
					this.OnCap_PersonasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dimenciones", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Dimenciones
		{
			get
			{
				return this._Dimenciones;
			}
			set
			{
				if ((this._Dimenciones != value))
				{
					this.OnDimencionesChanging(value);
					this.SendPropertyChanging();
					this._Dimenciones = value;
					this.SendPropertyChanged("Dimenciones");
					this.OnDimencionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10)")]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					if (this._EdificioTB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EdificioChanging(value);
					this.SendPropertyChanging();
					this._ID_Edificio = value;
					this.SendPropertyChanged("ID_Edificio");
					this.OnID_EdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_Capillas", Storage="_EdificioTB", ThisKey="ID_Edificio", OtherKey="ID_Edificio", IsForeignKey=true)]
		public EdificioTB EdificioTB
		{
			get
			{
				return this._EdificioTB.Entity;
			}
			set
			{
				EdificioTB previousValue = this._EdificioTB.Entity;
				if (((previousValue != value) 
							|| (this._EdificioTB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EdificioTB.Entity = null;
						previousValue.Capillas.Remove(this);
					}
					this._EdificioTB.Entity = value;
					if ((value != null))
					{
						value.Capillas.Add(this);
						this._ID_Edificio = value.ID_Edificio;
					}
					else
					{
						this._ID_Edificio = default(string);
					}
					this.SendPropertyChanged("EdificioTB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EdificioTB")]
	public partial class EdificioTB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Edificio;
		
		private string _Nombre_edificio;
		
		private string _Encargado;
		
		private int _Telefono;
		
		private string _E_Mail;
		
		private string _Dirección;
		
		private System.Nullable<int> _Estado;
		
		private EntitySet<Bodegas> _Bodegas;
		
		private EntitySet<Capillas> _Capillas;
		
		private EntitySet<EspacioTB> _EspacioTB;
		
		private EntitySet<Parqueos> _Parqueos;
		
		private EntitySet<Usuario> _Usuario;
		
		private EntitySet<TBusers> _TBusers;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EdificioChanging(string value);
    partial void OnID_EdificioChanged();
    partial void OnNombre_edificioChanging(string value);
    partial void OnNombre_edificioChanged();
    partial void OnEncargadoChanging(string value);
    partial void OnEncargadoChanged();
    partial void OnTelefonoChanging(int value);
    partial void OnTelefonoChanged();
    partial void OnE_MailChanging(string value);
    partial void OnE_MailChanged();
    partial void OnDirecciónChanging(string value);
    partial void OnDirecciónChanged();
    partial void OnEstadoChanging(System.Nullable<int> value);
    partial void OnEstadoChanged();
    #endregion
		
		public EdificioTB()
		{
			this._Bodegas = new EntitySet<Bodegas>(new Action<Bodegas>(this.attach_Bodegas), new Action<Bodegas>(this.detach_Bodegas));
			this._Capillas = new EntitySet<Capillas>(new Action<Capillas>(this.attach_Capillas), new Action<Capillas>(this.detach_Capillas));
			this._EspacioTB = new EntitySet<EspacioTB>(new Action<EspacioTB>(this.attach_EspacioTB), new Action<EspacioTB>(this.detach_EspacioTB));
			this._Parqueos = new EntitySet<Parqueos>(new Action<Parqueos>(this.attach_Parqueos), new Action<Parqueos>(this.detach_Parqueos));
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			this._TBusers = new EntitySet<TBusers>(new Action<TBusers>(this.attach_TBusers), new Action<TBusers>(this.detach_TBusers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					this.OnID_EdificioChanging(value);
					this.SendPropertyChanging();
					this._ID_Edificio = value;
					this.SendPropertyChanged("ID_Edificio");
					this.OnID_EdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_edificio", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Nombre_edificio
		{
			get
			{
				return this._Nombre_edificio;
			}
			set
			{
				if ((this._Nombre_edificio != value))
				{
					this.OnNombre_edificioChanging(value);
					this.SendPropertyChanging();
					this._Nombre_edificio = value;
					this.SendPropertyChanged("Nombre_edificio");
					this.OnNombre_edificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Encargado", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string Encargado
		{
			get
			{
				return this._Encargado;
			}
			set
			{
				if ((this._Encargado != value))
				{
					this.OnEncargadoChanging(value);
					this.SendPropertyChanging();
					this._Encargado = value;
					this.SendPropertyChanged("Encargado");
					this.OnEncargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int NOT NULL")]
		public int Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-Mail]", Storage="_E_Mail", DbType="NVarChar(20)")]
		public string E_Mail
		{
			get
			{
				return this._E_Mail;
			}
			set
			{
				if ((this._E_Mail != value))
				{
					this.OnE_MailChanging(value);
					this.SendPropertyChanging();
					this._E_Mail = value;
					this.SendPropertyChanged("E_Mail");
					this.OnE_MailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirección", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Dirección
		{
			get
			{
				return this._Dirección;
			}
			set
			{
				if ((this._Dirección != value))
				{
					this.OnDirecciónChanging(value);
					this.SendPropertyChanging();
					this._Dirección = value;
					this.SendPropertyChanged("Dirección");
					this.OnDirecciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_Bodegas", Storage="_Bodegas", ThisKey="ID_Edificio", OtherKey="ID_Edificio")]
		public EntitySet<Bodegas> Bodegas
		{
			get
			{
				return this._Bodegas;
			}
			set
			{
				this._Bodegas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_Capillas", Storage="_Capillas", ThisKey="ID_Edificio", OtherKey="ID_Edificio")]
		public EntitySet<Capillas> Capillas
		{
			get
			{
				return this._Capillas;
			}
			set
			{
				this._Capillas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_EspacioTB", Storage="_EspacioTB", ThisKey="ID_Edificio", OtherKey="ID_Edificio")]
		public EntitySet<EspacioTB> EspacioTB
		{
			get
			{
				return this._EspacioTB;
			}
			set
			{
				this._EspacioTB.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_Parqueos", Storage="_Parqueos", ThisKey="ID_Edificio", OtherKey="ID_Edificio")]
		public EntitySet<Parqueos> Parqueos
		{
			get
			{
				return this._Parqueos;
			}
			set
			{
				this._Parqueos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_Usuario", Storage="_Usuario", ThisKey="ID_Edificio", OtherKey="ID_Edificio")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_TBusers", Storage="_TBusers", ThisKey="ID_Edificio", OtherKey="ID_Edificio")]
		public EntitySet<TBusers> TBusers
		{
			get
			{
				return this._TBusers;
			}
			set
			{
				this._TBusers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bodegas(Bodegas entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = this;
		}
		
		private void detach_Bodegas(Bodegas entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = null;
		}
		
		private void attach_Capillas(Capillas entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = this;
		}
		
		private void detach_Capillas(Capillas entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = null;
		}
		
		private void attach_EspacioTB(EspacioTB entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = this;
		}
		
		private void detach_EspacioTB(EspacioTB entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = null;
		}
		
		private void attach_Parqueos(Parqueos entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = this;
		}
		
		private void detach_Parqueos(Parqueos entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = null;
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = null;
		}
		
		private void attach_TBusers(TBusers entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = this;
		}
		
		private void detach_TBusers(TBusers entity)
		{
			this.SendPropertyChanging();
			entity.EdificioTB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Enseres")]
	public partial class Enseres : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Enser;
		
		private string _Marca;
		
		private string _Tipo;
		
		private int _Estado;
		
		private string _ID_Espacio;
		
		private EntityRef<EspacioTB> _EspacioTB;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EnserChanging(string value);
    partial void OnID_EnserChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnID_EspacioChanging(string value);
    partial void OnID_EspacioChanged();
    #endregion
		
		public Enseres()
		{
			this._EspacioTB = default(EntityRef<EspacioTB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Enser", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Enser
		{
			get
			{
				return this._ID_Enser;
			}
			set
			{
				if ((this._ID_Enser != value))
				{
					this.OnID_EnserChanging(value);
					this.SendPropertyChanging();
					this._ID_Enser = value;
					this.SendPropertyChanged("ID_Enser");
					this.OnID_EnserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Espacio", DbType="NVarChar(10)")]
		public string ID_Espacio
		{
			get
			{
				return this._ID_Espacio;
			}
			set
			{
				if ((this._ID_Espacio != value))
				{
					if (this._EspacioTB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EspacioChanging(value);
					this.SendPropertyChanging();
					this._ID_Espacio = value;
					this.SendPropertyChanged("ID_Espacio");
					this.OnID_EspacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EspacioTB_Enseres", Storage="_EspacioTB", ThisKey="ID_Espacio", OtherKey="ID_Espacio", IsForeignKey=true)]
		public EspacioTB EspacioTB
		{
			get
			{
				return this._EspacioTB.Entity;
			}
			set
			{
				EspacioTB previousValue = this._EspacioTB.Entity;
				if (((previousValue != value) 
							|| (this._EspacioTB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EspacioTB.Entity = null;
						previousValue.Enseres.Remove(this);
					}
					this._EspacioTB.Entity = value;
					if ((value != null))
					{
						value.Enseres.Add(this);
						this._ID_Espacio = value.ID_Espacio;
					}
					else
					{
						this._ID_Espacio = default(string);
					}
					this.SendPropertyChanged("EspacioTB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EspacioTB")]
	public partial class EspacioTB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Espacio;
		
		private string _Tipo;
		
		private int _Capacidad;
		
		private string _Dimensiones;
		
		private int _Estado;
		
		private string _ID_Edificio;
		
		private EntitySet<Enseres> _Enseres;
		
		private EntitySet<Insidencias> _Insidencias;
		
		private EntityRef<EdificioTB> _EdificioTB;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EspacioChanging(string value);
    partial void OnID_EspacioChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnCapacidadChanging(int value);
    partial void OnCapacidadChanged();
    partial void OnDimensionesChanging(string value);
    partial void OnDimensionesChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnID_EdificioChanging(string value);
    partial void OnID_EdificioChanged();
    #endregion
		
		public EspacioTB()
		{
			this._Enseres = new EntitySet<Enseres>(new Action<Enseres>(this.attach_Enseres), new Action<Enseres>(this.detach_Enseres));
			this._Insidencias = new EntitySet<Insidencias>(new Action<Insidencias>(this.attach_Insidencias), new Action<Insidencias>(this.detach_Insidencias));
			this._EdificioTB = default(EntityRef<EdificioTB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Espacio", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Espacio
		{
			get
			{
				return this._ID_Espacio;
			}
			set
			{
				if ((this._ID_Espacio != value))
				{
					this.OnID_EspacioChanging(value);
					this.SendPropertyChanging();
					this._ID_Espacio = value;
					this.SendPropertyChanged("ID_Espacio");
					this.OnID_EspacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacidad", DbType="Int NOT NULL")]
		public int Capacidad
		{
			get
			{
				return this._Capacidad;
			}
			set
			{
				if ((this._Capacidad != value))
				{
					this.OnCapacidadChanging(value);
					this.SendPropertyChanging();
					this._Capacidad = value;
					this.SendPropertyChanged("Capacidad");
					this.OnCapacidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dimensiones", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Dimensiones
		{
			get
			{
				return this._Dimensiones;
			}
			set
			{
				if ((this._Dimensiones != value))
				{
					this.OnDimensionesChanging(value);
					this.SendPropertyChanging();
					this._Dimensiones = value;
					this.SendPropertyChanged("Dimensiones");
					this.OnDimensionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10)")]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					if (this._EdificioTB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EdificioChanging(value);
					this.SendPropertyChanging();
					this._ID_Edificio = value;
					this.SendPropertyChanged("ID_Edificio");
					this.OnID_EdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EspacioTB_Enseres", Storage="_Enseres", ThisKey="ID_Espacio", OtherKey="ID_Espacio")]
		public EntitySet<Enseres> Enseres
		{
			get
			{
				return this._Enseres;
			}
			set
			{
				this._Enseres.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EspacioTB_Insidencias", Storage="_Insidencias", ThisKey="ID_Espacio", OtherKey="ID_Espacio")]
		public EntitySet<Insidencias> Insidencias
		{
			get
			{
				return this._Insidencias;
			}
			set
			{
				this._Insidencias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_EspacioTB", Storage="_EdificioTB", ThisKey="ID_Edificio", OtherKey="ID_Edificio", IsForeignKey=true)]
		public EdificioTB EdificioTB
		{
			get
			{
				return this._EdificioTB.Entity;
			}
			set
			{
				EdificioTB previousValue = this._EdificioTB.Entity;
				if (((previousValue != value) 
							|| (this._EdificioTB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EdificioTB.Entity = null;
						previousValue.EspacioTB.Remove(this);
					}
					this._EdificioTB.Entity = value;
					if ((value != null))
					{
						value.EspacioTB.Add(this);
						this._ID_Edificio = value.ID_Edificio;
					}
					else
					{
						this._ID_Edificio = default(string);
					}
					this.SendPropertyChanged("EdificioTB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Enseres(Enseres entity)
		{
			this.SendPropertyChanging();
			entity.EspacioTB = this;
		}
		
		private void detach_Enseres(Enseres entity)
		{
			this.SendPropertyChanging();
			entity.EspacioTB = null;
		}
		
		private void attach_Insidencias(Insidencias entity)
		{
			this.SendPropertyChanging();
			entity.EspacioTB = this;
		}
		
		private void detach_Insidencias(Insidencias entity)
		{
			this.SendPropertyChanging();
			entity.EspacioTB = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Insidencias")]
	public partial class Insidencias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Insidencia;
		
		private string _Descripción;
		
		private string _Situación;
		
		private int _Estado;
		
		private string _ID_Espacio;
		
		private EntityRef<EspacioTB> _EspacioTB;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_InsidenciaChanging(string value);
    partial void OnID_InsidenciaChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    partial void OnSituaciónChanging(string value);
    partial void OnSituaciónChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnID_EspacioChanging(string value);
    partial void OnID_EspacioChanged();
    #endregion
		
		public Insidencias()
		{
			this._EspacioTB = default(EntityRef<EspacioTB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Insidencia", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Insidencia
		{
			get
			{
				return this._ID_Insidencia;
			}
			set
			{
				if ((this._ID_Insidencia != value))
				{
					this.OnID_InsidenciaChanging(value);
					this.SendPropertyChanging();
					this._ID_Insidencia = value;
					this.SendPropertyChanged("ID_Insidencia");
					this.OnID_InsidenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Situación", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Situación
		{
			get
			{
				return this._Situación;
			}
			set
			{
				if ((this._Situación != value))
				{
					this.OnSituaciónChanging(value);
					this.SendPropertyChanging();
					this._Situación = value;
					this.SendPropertyChanged("Situación");
					this.OnSituaciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Espacio", DbType="NVarChar(10)")]
		public string ID_Espacio
		{
			get
			{
				return this._ID_Espacio;
			}
			set
			{
				if ((this._ID_Espacio != value))
				{
					if (this._EspacioTB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EspacioChanging(value);
					this.SendPropertyChanging();
					this._ID_Espacio = value;
					this.SendPropertyChanged("ID_Espacio");
					this.OnID_EspacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EspacioTB_Insidencias", Storage="_EspacioTB", ThisKey="ID_Espacio", OtherKey="ID_Espacio", IsForeignKey=true)]
		public EspacioTB EspacioTB
		{
			get
			{
				return this._EspacioTB.Entity;
			}
			set
			{
				EspacioTB previousValue = this._EspacioTB.Entity;
				if (((previousValue != value) 
							|| (this._EspacioTB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EspacioTB.Entity = null;
						previousValue.Insidencias.Remove(this);
					}
					this._EspacioTB.Entity = value;
					if ((value != null))
					{
						value.Insidencias.Add(this);
						this._ID_Espacio = value.ID_Espacio;
					}
					else
					{
						this._ID_Espacio = default(string);
					}
					this.SendPropertyChanged("EspacioTB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parqueos")]
	public partial class Parqueos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Parqueo;
		
		private int _Cap_Vehiculos;
		
		private string _Dimenciones;
		
		private int _Estado;
		
		private string _ID_Edificio;
		
		private EntityRef<EdificioTB> _EdificioTB;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ParqueoChanging(string value);
    partial void OnID_ParqueoChanged();
    partial void OnCap_VehiculosChanging(int value);
    partial void OnCap_VehiculosChanged();
    partial void OnDimencionesChanging(string value);
    partial void OnDimencionesChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnID_EdificioChanging(string value);
    partial void OnID_EdificioChanged();
    #endregion
		
		public Parqueos()
		{
			this._EdificioTB = default(EntityRef<EdificioTB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Parqueo", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Parqueo
		{
			get
			{
				return this._ID_Parqueo;
			}
			set
			{
				if ((this._ID_Parqueo != value))
				{
					this.OnID_ParqueoChanging(value);
					this.SendPropertyChanging();
					this._ID_Parqueo = value;
					this.SendPropertyChanged("ID_Parqueo");
					this.OnID_ParqueoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap_Vehiculos", DbType="Int NOT NULL")]
		public int Cap_Vehiculos
		{
			get
			{
				return this._Cap_Vehiculos;
			}
			set
			{
				if ((this._Cap_Vehiculos != value))
				{
					this.OnCap_VehiculosChanging(value);
					this.SendPropertyChanging();
					this._Cap_Vehiculos = value;
					this.SendPropertyChanged("Cap_Vehiculos");
					this.OnCap_VehiculosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dimenciones", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Dimenciones
		{
			get
			{
				return this._Dimenciones;
			}
			set
			{
				if ((this._Dimenciones != value))
				{
					this.OnDimencionesChanging(value);
					this.SendPropertyChanging();
					this._Dimenciones = value;
					this.SendPropertyChanged("Dimenciones");
					this.OnDimencionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10)")]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					if (this._EdificioTB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EdificioChanging(value);
					this.SendPropertyChanging();
					this._ID_Edificio = value;
					this.SendPropertyChanged("ID_Edificio");
					this.OnID_EdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_Parqueos", Storage="_EdificioTB", ThisKey="ID_Edificio", OtherKey="ID_Edificio", IsForeignKey=true)]
		public EdificioTB EdificioTB
		{
			get
			{
				return this._EdificioTB.Entity;
			}
			set
			{
				EdificioTB previousValue = this._EdificioTB.Entity;
				if (((previousValue != value) 
							|| (this._EdificioTB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EdificioTB.Entity = null;
						previousValue.Parqueos.Remove(this);
					}
					this._EdificioTB.Entity = value;
					if ((value != null))
					{
						value.Parqueos.Add(this);
						this._ID_Edificio = value.ID_Edificio;
					}
					else
					{
						this._ID_Edificio = default(string);
					}
					this.SendPropertyChanged("EdificioTB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Roles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Rol;
		
		private string _Nombre_Rol;
		
		private string _Descrip_Rol;
		
		private int _Estado;
		
		private decimal _Salario;
		
		private EntitySet<Usuario> _Usuario;
		
		private EntitySet<TBusers> _TBusers;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_RolChanging(int value);
    partial void OnID_RolChanged();
    partial void OnNombre_RolChanging(string value);
    partial void OnNombre_RolChanged();
    partial void OnDescrip_RolChanging(string value);
    partial void OnDescrip_RolChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnSalarioChanging(decimal value);
    partial void OnSalarioChanged();
    #endregion
		
		public Roles()
		{
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			this._TBusers = new EntitySet<TBusers>(new Action<TBusers>(this.attach_TBusers), new Action<TBusers>(this.detach_TBusers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Rol", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Rol
		{
			get
			{
				return this._ID_Rol;
			}
			set
			{
				if ((this._ID_Rol != value))
				{
					this.OnID_RolChanging(value);
					this.SendPropertyChanging();
					this._ID_Rol = value;
					this.SendPropertyChanged("ID_Rol");
					this.OnID_RolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_Rol", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string Nombre_Rol
		{
			get
			{
				return this._Nombre_Rol;
			}
			set
			{
				if ((this._Nombre_Rol != value))
				{
					this.OnNombre_RolChanging(value);
					this.SendPropertyChanging();
					this._Nombre_Rol = value;
					this.SendPropertyChanged("Nombre_Rol");
					this.OnNombre_RolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrip_Rol", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descrip_Rol
		{
			get
			{
				return this._Descrip_Rol;
			}
			set
			{
				if ((this._Descrip_Rol != value))
				{
					this.OnDescrip_RolChanging(value);
					this.SendPropertyChanging();
					this._Descrip_Rol = value;
					this.SendPropertyChanged("Descrip_Rol");
					this.OnDescrip_RolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salario", DbType="Money NOT NULL")]
		public decimal Salario
		{
			get
			{
				return this._Salario;
			}
			set
			{
				if ((this._Salario != value))
				{
					this.OnSalarioChanging(value);
					this.SendPropertyChanging();
					this._Salario = value;
					this.SendPropertyChanged("Salario");
					this.OnSalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_Usuario", Storage="_Usuario", ThisKey="ID_Rol", OtherKey="ID_Rol")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_TBusers", Storage="_TBusers", ThisKey="ID_Rol", OtherKey="ID_Rol")]
		public EntitySet<TBusers> TBusers
		{
			get
			{
				return this._TBusers;
			}
			set
			{
				this._TBusers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Roles = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Roles = null;
		}
		
		private void attach_TBusers(TBusers entity)
		{
			this.SendPropertyChanging();
			entity.Roles = this;
		}
		
		private void detach_TBusers(TBusers entity)
		{
			this.SendPropertyChanging();
			entity.Roles = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Usuario;
		
		private string _Nombre;
		
		private string _Usuario1;
		
		private System.Data.Linq.Binary _Contraseña;
		
		private string _Direccion;
		
		private System.Nullable<int> _Telefono;
		
		private string _E_Mail;
		
		private int _Estado;
		
		private string _ID_Edificio;
		
		private System.Nullable<int> _ID_Rol;
		
		private EntityRef<EdificioTB> _EdificioTB;
		
		private EntityRef<Roles> _Roles;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UsuarioChanging(string value);
    partial void OnID_UsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUsuario1Changing(string value);
    partial void OnUsuario1Changed();
    partial void OnContraseñaChanging(System.Data.Linq.Binary value);
    partial void OnContraseñaChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(System.Nullable<int> value);
    partial void OnTelefonoChanged();
    partial void OnE_MailChanging(string value);
    partial void OnE_MailChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    partial void OnID_EdificioChanging(string value);
    partial void OnID_EdificioChanged();
    partial void OnID_RolChanging(System.Nullable<int> value);
    partial void OnID_RolChanged();
    #endregion
		
		public Usuario()
		{
			this._EdificioTB = default(EntityRef<EdificioTB>);
			this._Roles = default(EntityRef<Roles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Usuario
		{
			get
			{
				return this._ID_Usuario;
			}
			set
			{
				if ((this._ID_Usuario != value))
				{
					this.OnID_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Usuario = value;
					this.SendPropertyChanged("ID_Usuario");
					this.OnID_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Usuario", Storage="_Usuario1", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Usuario1
		{
			get
			{
				return this._Usuario1;
			}
			set
			{
				if ((this._Usuario1 != value))
				{
					this.OnUsuario1Changing(value);
					this.SendPropertyChanging();
					this._Usuario1 = value;
					this.SendPropertyChanged("Usuario1");
					this.OnUsuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarBinary(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(20)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int")]
		public System.Nullable<int> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-Mail]", Storage="_E_Mail", DbType="NVarChar(25)")]
		public string E_Mail
		{
			get
			{
				return this._E_Mail;
			}
			set
			{
				if ((this._E_Mail != value))
				{
					this.OnE_MailChanging(value);
					this.SendPropertyChanging();
					this._E_Mail = value;
					this.SendPropertyChanged("E_Mail");
					this.OnE_MailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10)")]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					if (this._EdificioTB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EdificioChanging(value);
					this.SendPropertyChanging();
					this._ID_Edificio = value;
					this.SendPropertyChanged("ID_Edificio");
					this.OnID_EdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Rol", DbType="Int")]
		public System.Nullable<int> ID_Rol
		{
			get
			{
				return this._ID_Rol;
			}
			set
			{
				if ((this._ID_Rol != value))
				{
					if (this._Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_RolChanging(value);
					this.SendPropertyChanging();
					this._ID_Rol = value;
					this.SendPropertyChanged("ID_Rol");
					this.OnID_RolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_Usuario", Storage="_EdificioTB", ThisKey="ID_Edificio", OtherKey="ID_Edificio", IsForeignKey=true)]
		public EdificioTB EdificioTB
		{
			get
			{
				return this._EdificioTB.Entity;
			}
			set
			{
				EdificioTB previousValue = this._EdificioTB.Entity;
				if (((previousValue != value) 
							|| (this._EdificioTB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EdificioTB.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._EdificioTB.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._ID_Edificio = value.ID_Edificio;
					}
					else
					{
						this._ID_Edificio = default(string);
					}
					this.SendPropertyChanged("EdificioTB");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_Usuario", Storage="_Roles", ThisKey="ID_Rol", OtherKey="ID_Rol", IsForeignKey=true)]
		public Roles Roles
		{
			get
			{
				return this._Roles.Entity;
			}
			set
			{
				Roles previousValue = this._Roles.Entity;
				if (((previousValue != value) 
							|| (this._Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Roles.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Roles.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._ID_Rol = value.ID_Rol;
					}
					else
					{
						this._ID_Rol = default(Nullable<int>);
					}
					this.SendPropertyChanged("Roles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBusers")]
	public partial class TBusers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_User;
		
		private string _Nombre;
		
		private string _Usuario;
		
		private string _Pass;
		
		private string _Dire;
		
		private System.Nullable<int> _Telefono;
		
		private string _E_maul;
		
		private System.Nullable<int> _Estado;
		
		private string _ID_Edificio;
		
		private int _ID_Rol;
		
		private EntityRef<EdificioTB> _EdificioTB;
		
		private EntityRef<Roles> _Roles;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UserChanging(string value);
    partial void OnID_UserChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnDireChanging(string value);
    partial void OnDireChanged();
    partial void OnTelefonoChanging(System.Nullable<int> value);
    partial void OnTelefonoChanged();
    partial void OnE_maulChanging(string value);
    partial void OnE_maulChanged();
    partial void OnEstadoChanging(System.Nullable<int> value);
    partial void OnEstadoChanged();
    partial void OnID_EdificioChanging(string value);
    partial void OnID_EdificioChanged();
    partial void OnID_RolChanging(int value);
    partial void OnID_RolChanged();
    #endregion
		
		public TBusers()
		{
			this._EdificioTB = default(EntityRef<EdificioTB>);
			this._Roles = default(EntityRef<Roles>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_User", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_User
		{
			get
			{
				return this._ID_User;
			}
			set
			{
				if ((this._ID_User != value))
				{
					this.OnID_UserChanging(value);
					this.SendPropertyChanging();
					this._ID_User = value;
					this.SendPropertyChanged("ID_User");
					this.OnID_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dire", DbType="NVarChar(50)")]
		public string Dire
		{
			get
			{
				return this._Dire;
			}
			set
			{
				if ((this._Dire != value))
				{
					this.OnDireChanging(value);
					this.SendPropertyChanging();
					this._Dire = value;
					this.SendPropertyChanged("Dire");
					this.OnDireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int")]
		public System.Nullable<int> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-maul]", Storage="_E_maul", DbType="NVarChar(50)")]
		public string E_maul
		{
			get
			{
				return this._E_maul;
			}
			set
			{
				if ((this._E_maul != value))
				{
					this.OnE_maulChanging(value);
					this.SendPropertyChanging();
					this._E_maul = value;
					this.SendPropertyChanged("E_maul");
					this.OnE_maulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					if (this._EdificioTB.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EdificioChanging(value);
					this.SendPropertyChanging();
					this._ID_Edificio = value;
					this.SendPropertyChanged("ID_Edificio");
					this.OnID_EdificioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Rol", DbType="Int NOT NULL")]
		public int ID_Rol
		{
			get
			{
				return this._ID_Rol;
			}
			set
			{
				if ((this._ID_Rol != value))
				{
					if (this._Roles.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_RolChanging(value);
					this.SendPropertyChanging();
					this._ID_Rol = value;
					this.SendPropertyChanged("ID_Rol");
					this.OnID_RolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EdificioTB_TBusers", Storage="_EdificioTB", ThisKey="ID_Edificio", OtherKey="ID_Edificio", IsForeignKey=true)]
		public EdificioTB EdificioTB
		{
			get
			{
				return this._EdificioTB.Entity;
			}
			set
			{
				EdificioTB previousValue = this._EdificioTB.Entity;
				if (((previousValue != value) 
							|| (this._EdificioTB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EdificioTB.Entity = null;
						previousValue.TBusers.Remove(this);
					}
					this._EdificioTB.Entity = value;
					if ((value != null))
					{
						value.TBusers.Add(this);
						this._ID_Edificio = value.ID_Edificio;
					}
					else
					{
						this._ID_Edificio = default(string);
					}
					this.SendPropertyChanged("EdificioTB");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Roles_TBusers", Storage="_Roles", ThisKey="ID_Rol", OtherKey="ID_Rol", IsForeignKey=true)]
		public Roles Roles
		{
			get
			{
				return this._Roles.Entity;
			}
			set
			{
				Roles previousValue = this._Roles.Entity;
				if (((previousValue != value) 
							|| (this._Roles.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Roles.Entity = null;
						previousValue.TBusers.Remove(this);
					}
					this._Roles.Entity = value;
					if ((value != null))
					{
						value.TBusers.Add(this);
						this._ID_Rol = value.ID_Rol;
					}
					else
					{
						this._ID_Rol = default(int);
					}
					this.SendPropertyChanged("Roles");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class ListarEdificiosResult
	{
		
		private string _ID_Edificio;
		
		private string _Nombre_edificio;
		
		private string _Encargado;
		
		private int _Telefono;
		
		private string _E_Mail;
		
		private string _Dirección;
		
		private System.Nullable<int> _Estado;
		
		public ListarEdificiosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					this._ID_Edificio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_edificio", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Nombre_edificio
		{
			get
			{
				return this._Nombre_edificio;
			}
			set
			{
				if ((this._Nombre_edificio != value))
				{
					this._Nombre_edificio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Encargado", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string Encargado
		{
			get
			{
				return this._Encargado;
			}
			set
			{
				if ((this._Encargado != value))
				{
					this._Encargado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int NOT NULL")]
		public int Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-Mail]", Storage="_E_Mail", DbType="NVarChar(20)")]
		public string E_Mail
		{
			get
			{
				return this._E_Mail;
			}
			set
			{
				if ((this._E_Mail != value))
				{
					this._E_Mail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirección", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Dirección
		{
			get
			{
				return this._Dirección;
			}
			set
			{
				if ((this._Dirección != value))
				{
					this._Dirección = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class ListarEnseresResult
	{
		
		private string _ID_Enser;
		
		private string _Marca;
		
		private string _Tipo;
		
		private int _Estado;
		
		private string _ID_Espacio;
		
		public ListarEnseresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Enser", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Enser
		{
			get
			{
				return this._ID_Enser;
			}
			set
			{
				if ((this._ID_Enser != value))
				{
					this._ID_Enser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this._Marca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Espacio", DbType="NVarChar(10)")]
		public string ID_Espacio
		{
			get
			{
				return this._ID_Espacio;
			}
			set
			{
				if ((this._ID_Espacio != value))
				{
					this._ID_Espacio = value;
				}
			}
		}
	}
	
	public partial class ListarEspaciosResult
	{
		
		private string _ID_Espacio;
		
		private string _Tipo;
		
		private int _Capacidad;
		
		private string _Dimensiones;
		
		private int _Estado;
		
		private string _ID_Edificio;
		
		public ListarEspaciosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Espacio", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Espacio
		{
			get
			{
				return this._ID_Espacio;
			}
			set
			{
				if ((this._ID_Espacio != value))
				{
					this._ID_Espacio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacidad", DbType="Int NOT NULL")]
		public int Capacidad
		{
			get
			{
				return this._Capacidad;
			}
			set
			{
				if ((this._Capacidad != value))
				{
					this._Capacidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dimensiones", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Dimensiones
		{
			get
			{
				return this._Dimensiones;
			}
			set
			{
				if ((this._Dimensiones != value))
				{
					this._Dimensiones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10)")]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					this._ID_Edificio = value;
				}
			}
		}
	}
	
	public partial class ListarUserResult
	{
		
		private string _ID_User;
		
		private string _Nombre;
		
		private string _Usuario;
		
		private string _Pass;
		
		private string _Dire;
		
		private System.Nullable<int> _Telefono;
		
		private string _E_maul;
		
		private System.Nullable<int> _Estado;
		
		private string _ID_Edificio;
		
		private int _ID_Rol;
		
		public ListarUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_User", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_User
		{
			get
			{
				return this._ID_User;
			}
			set
			{
				if ((this._ID_User != value))
				{
					this._ID_User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="Char(25) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this._Pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dire", DbType="NVarChar(50)")]
		public string Dire
		{
			get
			{
				return this._Dire;
			}
			set
			{
				if ((this._Dire != value))
				{
					this._Dire = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int")]
		public System.Nullable<int> Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-maul]", Storage="_E_maul", DbType="NVarChar(50)")]
		public string E_maul
		{
			get
			{
				return this._E_maul;
			}
			set
			{
				if ((this._E_maul != value))
				{
					this._E_maul = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Edificio", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ID_Edificio
		{
			get
			{
				return this._ID_Edificio;
			}
			set
			{
				if ((this._ID_Edificio != value))
				{
					this._ID_Edificio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Rol", DbType="Int NOT NULL")]
		public int ID_Rol
		{
			get
			{
				return this._ID_Rol;
			}
			set
			{
				if ((this._ID_Rol != value))
				{
					this._ID_Rol = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
